version: '3.8'

services:
  scraper:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

  db:
    image: mysql:latest
    container_name: job_scraper_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PORT: ${DB_PORT}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: