# .github/workflows/deploy.yml

name: Build and deploy Python app to Azure Web App - JobAi-Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        working-directory: backEnd

      # Optional: Add step to run tests here

      - name: Prepare deployment package
        run: |
          cd backEnd
          zip -r ../release.zip .

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for verification (optional)
        run: unzip -l release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CE9FF6DF31DE478DA9661CCC080C7703 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_95F1873131004C64A1EDB2B706017D66 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_71BA684D58994A9A8CD2242D8BA940E7 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'JobAi-Backend'
          slot-name: 'Production'
          package: 'release.zip'
